#? Creation
name: FINAL
log: false
save: true

#? Validation and testing
# validation_interval: 50 # * In batches
validation_interval: 100
# validation_batches: 100
validation_batches: 10 # XXX
# test_interval: 50 # * In batches
test_interval: 100
# test_batches: 100
test_batches: 10 # XXX
# test_extra_logging_interval: 250
test_extra_logging_interval: 0

#? Datasets
train_datasets: [ALL_A]
validation_datasets: [UNSW]
test_datasets: [ALL_U]

#? Teeth
UNSW_train_teeth: 27
UNSW_test_teeth: 27
UNSW_validation_teeth: 27
AGFD_train_teeth: 15
AGFD_validation_teeth: 15
AGFD_test_teeth: 15
ASD_train_teeth: 15
ASD_validation_teeth: 15
ASD_test_teeth: 15
MCC5_train_teeth: 36
MCC5_validation_teeth: 36
MCC5_test_teeth: 36

class_map:
    healthy: 0
    crack: 1
    wear: 2
    # pitting: 3
    # missing_tooth: 4

use_difference: true
episodic_training: false
average_over_anchors: true # Only works for non-episodic training

# Only for validation and testing when using non-episodic training
k_shot: 10
n_query: 10

#* ALL [TRAIN]
separate_dataset_batches: true # Only works for non-episodic training

# TRAIN
ALL_train_num_options: 5
ALL_train_num_anchors: 20
ALL_train_num_queries: 5
ALL_train_num_installations: 2

# TEST
ALL_test_num_options: 5
ALL_test_num_anchors: 20
ALL_test_num_queries: 5
ALL_test_num_installations: 2

#* UNSW [ALL]
##

UNSW_train_OT_method: nico # YYY
# UNSW_train_OT_method: signal # XXX: use this instead of Nico
UNSW_train_TSA_size: 40

# UNSW_train_speeds: [5, 10, 15, 20]
UNSW_train_speeds: [5, 15, 20] # XXX
UNSW_train_loads: [5, 10, 15, 20] # XXX: Added 20
# UNSW_train_loads: [5, 10] # XXX: removed 20
UNSW_train_classes: [healthy, crack]
UNSW_train_severities: [H, S, M, L] # * Needs both H & S

#* UNSW [ALL] (TEST)
##

# UNSW_train_OT_method: nico
UNSW_test_OT_method: signal # XXX: use this instead of Nico
UNSW_test_TSA_size: 40

UNSW_test_speeds: [5, 10, 15, 20]
UNSW_test_loads: [5, 10, 15, 20] # XXX: Add 20
UNSW_test_classes: [healthy, crack]
UNSW_test_severities: [H, S, M, L] # * Needs both H & S

#* MCC5-THU [ALL]
##

MCC5_train_OT_method: signal
MCC5_train_TSA_size: 30

MCC5_train_sensors: [gearbox_vibration_x]
# MCC5_train_sensors: [gearbox_vibration_x, gearbox_vibration_y]
MCC5_train_speeds: [1000, 1500, 2000, 2500, 3000]
MCC5_train_loads: [5, 10, 15, 20]
MCC5_train_classes: [healthy, crack, wear]
MCC5_train_severities: [M, L]

#* MCC5-THU [ALL] [TEST]
##

MCC5_test_OT_method: signal
MCC5_test_TSA_size: 30

MCC5_test_sensors: [gearbox_vibration_x]
# MCC5_test_sensors: [gearbox_vibration_x, gearbox_vibration_y]
MCC5_test_speeds: [1000, 1500, 2000, 2500, 3000]
MCC5_test_loads: [5, 10, 15, 20]
MCC5_test_classes: [healthy, crack, wear]
MCC5_test_severities: [M, L]

#* AGFD [ALL]
##

AGFD_train_OT_method: signal
AGFD_train_TSA_size: 40

AGFD_train_sensors: [acc4]
AGFD_train_speeds: [500, 750, 1000, 1250, 1500] # Skip 250 # XXX: Add 1500
AGFD_train_loads: [1, 6, 11] # XXX: Add 6
AGFD_train_installations: [1, 2, 3]
AGFD_train_healthy_GPs: [2, 3, 4, 5, 6, 9] # 1 & 7 not good, 8 doesn't exist # XXX: Drop 2 and 6
# AGFD_train_healthy_GPs: [2, 3, 4, 5, 6, 9] # 1 & 7 not good, 8 doesn't exist
AGFD_train_classes: [healthy, crack, wear]
AGFD_train_severities: [S, L]
AGFD_train_include_large_crack: false
AGFD_train_include_small_wear: false

#* AGFD [ALL] (TEST)
##

AGFD_test_OT_method: signal
AGFD_test_TSA_size: 40

AGFD_test_sensors: [acc4]
AGFD_test_speeds: [500, 750, 1000, 1250, 1500] # Skip 250 # XXX: ADd 1500
AGFD_test_loads: [1, 6, 11]
AGFD_test_installations: [1, 2, 3]
AGFD_test_healthy_GPs: [2, 3, 4, 5, 6, 9] # 1 & 7 not good, 8 doesn't exist # XXX: Drop 2 and 6
# AGFD_test_healthy_GPs: [2, 3, 4, 5, 6, 9] # 1 & 7 not good, 8 doesn't exist
AGFD_test_classes: [healthy, crack, wear]
AGFD_test_severities: [S, L]
AGFD_test_include_large_crack: false
AGFD_test_include_small_wear: false

#* ASD [ALL]
##

ASD_train_OT_method: signal # Unused (only option in ASD)
ASD_train_TSA_size: 45 # Unused (only option in ASD)

ASD_train_sensors: [acc4]
ASD_train_speeds: [500, 750, 1000, 1250] # Skip 250
ASD_train_loads: [1, 6, 11]
ASD_train_installations: [1, 2, 3]
ASD_train_healthy_GPs: [1, 4, 5, 7, 10]
ASD_train_classes: [healthy, 1-shim, 2-shim, 3-shim]
ASD_train_severities: [S, M, L]


#* UNSW VALIDATION
##

UNSW_validation_shift_methods: [load]

UNSW_validation_OT_methods: [signal]
UNSW_validation_TSA_sizes: [40]
UNSW_validation_speeds: [5, 10, 15, 20]
UNSW_validation_loads: [5, 10, 15]
UNSW_validation_classes: [healthy, crack]
UNSW_validation_severities: [H, S, M, L]

#* UNSW TEST
##

# UNSW_test_shift_methods: [load_and_severity]

# UNSW_test_OT_methods: [signal]
# UNSW_test_TSA_sizes: [40]
# UNSW_test_speeds: [5, 10, 15, 20]
# UNSW_test_loads: [5, 10, 15]
# UNSW_test_classes: [healthy, crack]
# UNSW_test_severities: [H, S, M, L]

# #* AGFD TEST
# ##

# AGFD_test_OT_method: signal
# AGFD_test_TSA_size: 40
# AGFD_test_shift_methods: [load]
# # AGFD_test_shift_methods: [load_and_installation]

# AGFD_test_sensors: [acc4]
# AGFD_test_speeds: [500, 750, 1000, 1250, 1500] # Skip 250 # XXX: ADd 1500
# AGFD_test_loads: [1, 6, 11]
# AGFD_test_installations: [1, 2, 3]
# AGFD_test_healthy_GPs: [2, 3, 4, 5, 6, 9] # 1 & 7 not good, 8 doesn't exist # XXX: Drop 2 and 6
# # AGFD_test_healthy_GPs: [2, 3, 4, 5, 6, 9] # 1 & 7 not good, 8 doesn't exist
# AGFD_test_classes: [healthy, crack, wear]
# AGFD_test_severities: [S, L]
# AGFD_test_include_large_crack: false
# AGFD_test_include_small_wear: false

#? Preprocessing
# * Order matters

preprocessing_individual: [cherry_pick_indices] # FIXME
preprocessing_batch: [amplitude_log10]
# preprocessing_difference_batch: [augment_amplitude]
preprocessing_difference_batch: [
        permutate_blocks,
        mask_blocks_non_episodic,
        # permute_within_blocks,
        augment_amplitude,
    ]
# preprocessing_difference_batch: [mask_blocks_non_episodic, augment_amplitude]

#? Preprocessing additional arguments
num_blocks_to_mask: 1 # Only `mask_blocks_non_episodic`
amplitude_augment_low: 0.5
amplitude_augment_high: 1.5
# amplitude_augment_low: 0.8
# amplitude_augment_high: 1.2
# Frequency cherry picking
# gear_harmonics_to_include: 10 # XXX
gear_harmonics_to_include: 8
gear_sideband_block_size: 5
# gear_sideband_block_size: 7 # !!!

#? Model

model: embedding

loss: triplet
loss_args:
    # margin: 2.0
    margin: 1.4
    miner: True
    miner_type: all
similarity: euclidean
lpnorm_embeddings_training: false
center_embeddings_inference: false
lpnorm_embeddings_inference: false

# ? Remember to set intermediate_L2 to True in the model_args
# loss: supcon
# loss_args:
#     temperature: 0.08
# similarity: cosine # Default: cosine
# lpnorm_embeddings_training: True # Default: True
# center_embeddings_inference: True
# lpnorm_embeddings_inference: True # Default: True

embedding_len: 2
backbone: MlpMixer
model_args:
    intermediate_L2: false
    num_layers: 3
    hidden_dim: 32
    tokens_mlp_dim: 16
    channels_mlp_dim: 64
    # hidden_dim: 21
    # tokens_mlp_dim: 16
    # channels_mlp_dim: 42

# ? Training

episodes_per_dataset_per_batch: 2 # FIXME: Automatically use number of datasets in training
max_batches: 901 # XXX
# max_batches: 1501
# max_batches: 501
# warmup_batches: 0 # XXX
warmup_batches: 100
lr: 0.001
# sch_gamma: 0.999 # XXX
sch_gamma: 0.998
momentum: 0.9
b2: 0.999
gradient_clip: 0 # XXX
# gradient_clip: 0.025 # HERE: Run results XXX: Maybe this is the one?
# gradient_clip: 2.5 

# Regularization
weight_decay: 0.0001
dropout: 0.1
# dropout: 0.3
